version: "3.7"
services:
  database:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
  chat-server:
    build:
      dockerfile: .DOCKERFILE
      context: ../../chat_server/
    restart: unless-stopped
    depends_on:
      - database
    ports:
      - "8080:80"
      - "4443:443"
  chat-client:
    build:
      dockerfile: dev.DOCKERFILE
      context: ../
    restart: unless-stopped
    stdin_open: true
    depends_on:
      - chat-server
    ports:
      - "3000:3000"
    privileged: true
volumes:
  mysql-data: