# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags' 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # chat client repository is checked out
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: chat_client
      # chat server repository is checked out
      - name: Checkout server repo
        uses: actions/checkout@v2
        with:
          repository: stefan-schlagh/chat_server
          path: chat_server
      # node.js setup
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: dir
      # install dependencies
      - name: npm install
        run: |
          cd ./chat_client
          npm install
      - run: dir 
      # build project
      - name: npm run build
        run: npm run build
        # set env CI to false -> ignore warnings
        env:
          CI: ""
      - run: dir 
      # build is copied to server
      - name: copy build to server
        run: |
          cd ../
          cp -r ./chat_client/build ./chat_server/build
      - name: check
        run: |
          cd ./chat_server
          dir
          cd ./build
          dir
